schoolsite/school_app/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('courses/', views.CourseListView.as_view(), name='courses'),
    path('courses/<int:pk>', views.CourseDetailView.as_view(), name='course_detail'),
    path('teachers/', views.TeacherListView.as_view(), name='teachers'),
    path('teachers/<int:pk>', views.TeacherDetailView.as_view(), name='teacher_detail'),
    path('tutors/', views.TutorListView.as_view(), name='tutors'),
    path('tutors/<int:pk>', views.TutorDetailView.as_view(), name='tutor_detail'),
    path('students/', views.StudentListView.as_view(), name='students'),
    path('students/<int:pk>', views.StudentDetailView.as_view(), name='student_detail'),
    path('lessons/', views.LessonListView.as_view(), name='lessons'),
    path('lessons/<int:pk>', views.LessonDetailView.as_view(), name='lesson_detail'),
    path('mygrades/', views.StudentGradesListView.as_view(), name='grades'),
    path('lessons/create/', views.LessonCreate.as_view(), name='lesson_create'),
    path('lessons/<int:pk>/delete/', views.LessonDelete.as_view(), name='lesson_delete'),
    path('grades/<int:pk>/update/', views.GradeUpdate.as_view(), name='grades_update')
]

schoolsite/schoolsite/urls.py
from django.contrib import admin
from django.urls import path, include
from school_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('school_app.urls')),
    path('', include('django.contrib.auth.urls')),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('signup/student/', views.StudentSignUpView.as_view(), name='student_signup'),
    path('signup/teacher/', views.TeacherSignUpView.as_view(), name='teacher_signup'),
    path('signup/tutor/', views.TutorSignUpView.as_view(), name='tutor_signup'),
]

schoolsite/school_app/models.py
from django.db import models
from django.urls import reverse
from django.db.models.signals import pre_save
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    """
    Модель для пользователя.
    Пользователь может принадлежать к одной из трех групп: студент, преподаватель, куратор.
    """
    is_student = models.BooleanField(default=False, verbose_name='Студент')
    is_teacher = models.BooleanField(default=False, verbose_name='Преподаватель')
    is_tutor = models.BooleanField(default=False, verbose_name='Куратор')


class Teacher(models.Model):
    """ Модель для преподавателя. """

    id = models.AutoField(primary_key=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, blank=False, verbose_name='Имя и фамилия преподавателя')
    email = models.EmailField(max_length=100, blank=True, null=True, verbose_name='E-mail преподавателя')
    role = models.CharField(max_length=20, blank=True, null=True, verbose_name='Роль преподавателя',
                            choices=[('Семинарист', 'Семинарист'), ('Лектор', 'Лектор')])
    education = models.CharField(max_length=100, blank=True, null=True, verbose_name='Образование преподавателя (ВУЗ)')
    company = models.CharField(max_length=100, blank=True, null=True, verbose_name='Компания')
    experience = models.SmallIntegerField(blank=True, null=True, verbose_name='Опыт в годах')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('teacher_detail', args=[str(self.id)])

    class Meta:
        ordering = ['name']


class Student(models.Model):
    """ Модель для студента. """

    id = models.AutoField(primary_key=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, blank=False, verbose_name='Имя студента')
    email = models.EmailField(max_length=100, blank=True, null=True, verbose_name='E-mail студента')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('student_detail', args=[str(self.id)])

    class Meta:
        ordering = ['name']


class Tutor(models.Model):
    """ Модель для куратора. """

    id = models.AutoField(primary_key=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=20, blank=False, verbose_name='Имя куратора')
    email = models.EmailField(max_length=100, blank=True, null=True, verbose_name='E-mail куратора')
    education = models.CharField(max_length=100, blank=True, null=True, verbose_name='Образование куратора')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('tutor_detail', args=[str(self.id)])

    class Meta:
        ordering = ['name']


class Course(models.Model):
    """ Модель для курса. """

    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50, blank=False, verbose_name='Название курса')
    description = models.TextField(blank=False, verbose_name='Описание курса')
    duration = models.PositiveSmallIntegerField(blank=False, default=6, verbose_name='Продолжительность курса',
                                                choices=[(6, '6 месяцев'), (12, '12 месяцев'), (18, '18 месяцев')])
    price = models.PositiveIntegerField(blank=False, default=50000, verbose_name='Стоимость курса')
    student = models.ManyToManyField(Student, through='Grade')
    teacher = models.ManyToManyField(Teacher)
    tutor = models.ManyToManyField(Tutor)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('course_detail', args=[str(self.id)])

    class Meta:
        ordering = ['id']


class Lesson(models.Model):
    """ Модель для урока. """

    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=40, blank=False, verbose_name='Тема занятия')
    course_id = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name='Курс')
    teacher_id = models.ForeignKey(Teacher, on_delete=models.SET_NULL, blank=True, null=True,
                                   verbose_name='Преподаватель')
    link = models.CharField(max_length=100, blank=True, null=True, verbose_name='Ссылка на занятие в Zoom')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('lesson_detail', args=[str(self.id)])

    class Meta:
        ordering = ['course_id']


class Grade(models.Model):
    """ Модель для оценок. """

    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name='Курс')
    student = models.ForeignKey(Student, on_delete=models.CASCADE, verbose_name='Студент')
    homework1 = models.SmallIntegerField(blank=True, null=True, verbose_name='Оценка за 1 ДЗ',
                                         choices=[(2, 2), (3, 3), (4, 4), (5, 5)])
    homework2 = models.SmallIntegerField(blank=True, null=True, verbose_name='Оценка за 2 ДЗ',
                                         choices=[(2, 2), (3, 3), (4, 4), (5, 5)])
    project = models.SmallIntegerField(blank=True, null=True, verbose_name='Оценка за проект',
                                       choices=[(2, 2), (3, 3), (4, 4), (5, 5)])
    final_mark = models.FloatField(blank=True, null=True, verbose_name='Оценка за курс')

    class Meta:
        ordering = ['course']


def calc_online_school_stats():
    """ Расчёт основных показателей онлайн-школы для вывода на главной странице. """

    num_courses = Course.objects.all().count()
    num_teachers = Teacher.objects.all().count()
    num_students = Student.objects.all().count()
    return num_courses, num_teachers, num_students


def calc_student_final_mark(instance, **kwargs):
    """ Автоматический расчёт итоговой оценки за курс, если выставлены оценки за ДЗ1, ДЗ2 и проект. """

    if instance.homework1 and instance.homework2 and instance.project:
        instance.final_mark = 1 / 3 * sum([instance.homework1, instance.homework2, instance.project])
    return instance.final_mark


pre_save.connect(calc_student_final_mark, sender=Grade, dispatch_uid=__file__)
def calc_online_school_stats():
    """ Расчёт основных показателей онлайн-школы для вывода на главной странице. """

    num_courses = Course.objects.all().count()
    num_teachers = Teacher.objects.all().count()
    num_students = Student.objects.all().count()
    return num_courses, num_teachers, num_students


def calc_student_final_mark(instance, **kwargs):
    """ Автоматический расчёт итоговой оценки за курс, если выставлены оценки за ДЗ1, ДЗ2 и проект. """

    if instance.homework1 and instance.homework2 and instance.project:
        instance.final_mark = 1 / 3 * sum([instance.homework1, instance.homework2, instance.project])
    return instance.final_mark


pre_save.connect(calc_student_final_mark, sender=Grade, dispatch_uid=__file__)

schoolsite/school_app/views.py
from django.shortcuts import render
from django.views import generic
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import login
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView, UpdateView, DeleteView
from school_app.forms import StudentSignUpForm, TeacherSignUpForm, TutorSignUpForm
from school_app.models import calc_online_school_stats
from school_app.models import User, Course, Teacher, Student, Tutor, Lesson, Grade
from school_app.filters import CourseFilter, TeacherFilter, StudentFilter, TutorFilter, LessonFilter
from school_app.decorators import teacher_required, student_required, tutor_required


class CourseListView(generic.ListView):
    """ Отображение информации о курсах. """

    model = Course

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = CourseFilter(self.request.GET, queryset=self.get_queryset())
        return context


class CourseDetailView(generic.DetailView):
    """ Отображение детальной информации о курсе. """
    model = Course


class TeacherListView(generic.ListView):
    """ Отображение информации о преподавателях. """
    model = Teacher

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = TeacherFilter(self.request.GET, queryset=self.get_queryset())
        return context


class TeacherDetailView(generic.DetailView):
    """ Отображение детальной информации о преподавателе. """
    model = Teacher


class StudentListView(LoginRequiredMixin, generic.ListView):
    """ Отображение информации о студентах. """

    model = Student
    login_url = '/login/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = StudentFilter(self.request.GET, queryset=self.get_queryset())
        return context


class StudentDetailView(generic.DetailView):
    """ Отображение детальной информации о студенте. """
    model = Student


class TutorListView(LoginRequiredMixin, generic.ListView):
    """ Отображение информации о кураторах. """

    model = Tutor
    login_url = '/login/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = TutorFilter(self.request.GET, queryset=self.get_queryset())
        return context


class MentorDetailView(generic.DetailView):
    """ Отображение детальной информации о кураторе. """
    model = Tutor


class LessonListView(LoginRequiredMixin, generic.ListView):
    """ Отображение информации об уроках. """

    model = Lesson
    login_url = '/login/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = LessonFilter(self.request.GET, queryset=self.get_queryset())
        return context

    def get_queryset(self):
        if self.request.user.is_student:
            return Lesson.objects.filter(course_id__student__user=self.request.user)
        else:
            return Lesson.objects.all()


class LessonDetailView(generic.DetailView):
    """ Отображение с детальной информацией об уроке. """
    model = Lesson


class SignUpView(TemplateView):
    """ Отображение для регистрации. """
    template_name = 'registration/signup.html'


class StudentSignUpView(CreateView):
    """ Отображение для регистрации студента. """

    model = User
    form_class = StudentSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'student'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return index(self.request)


class TeacherSignUpView(CreateView):
    """ Отображение для регистрации преподавателя. """

    model = User
    form_class = TeacherSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'teacher'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return index(self.request)


class TutorSignUpView(CreateView):
    """ Отображение для регистрации куратора. """

    model = User
    form_class = TutorSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'tutor'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return index(self.request)


@method_decorator([login_required, student_required], name='dispatch')
class StudentGradesListView(LoginRequiredMixin, generic.ListView):
    """ Отображение оценок студента. """

    model = Student
    template_name ='school_app/student_grades_list.html'

    def get_queryset(self):
        return Student.objects.filter(user=self.request.user)


@method_decorator([login_required, teacher_required], name='dispatch')
class LessonCreate(CreateView):
    """ Отображение для создания урока. """

    model = Lesson
    fields = ['title', 'course_id', 'teacher_id', 'link']
    success_url = reverse_lazy('lessons')


@method_decorator([login_required, teacher_required], name='dispatch')
class LessonDelete(DeleteView):
    """ Отображение для удаления урока. """

    model = Lesson
    success_url = reverse_lazy('lessons')


@method_decorator([login_required, teacher_required], name='dispatch')
class GradeUpdate(UpdateView):
    """ Отображение для изменения урока. """

    model = Grade
    fields = ['course', 'student', 'homework1', 'homework2', 'project', 'final_mark']
    success_url = reverse_lazy('students')


def index(request):
    """ Функция отображения для домашней страницы сайта. """

    num_courses, num_teachers, num_students = calc_online_school_stats()
    return render(request, 'index.html',
                  context={'num_courses': num_courses,
                           'num_teachers': num_teachers,
                           'num_students': num_students})

schoolsite/school_app/templates/school_app/course_detail.html
{% extends "base_generic.html" %}

{% block content %}
  {% if course %}
  <h1>Курс: {{ course.name }}</h1>

  <p><strong>Описание:</strong> {{ course.description }}</p>
  <p><strong>Длительность:</strong> {{ course.duration }} месяцев.</p>
  <p><strong>Стоимость:</strong> {{ course.price }} рублей.</p>

  {% if course.teacher.all %}
  <p><strong>Преподаватели:</strong>
      {% for teacher in course.teacher.all %}
          <a href="{{ teacher.get_absolute_url }}">
              {{ teacher.name }}
          </a> ({{ teacher.company }})
          {% if not forloop.last %}, {% endif %}
      {% endfor %}
  </p>
  {% endif %}

  {% if course.tutor.all %}
  <p><strong>Кураторы:</strong>
      {% for tutor in course.tutor.all %}
          <a href="{{ tutor.get_absolute_url }}">
              {{ tutor.name }}
          </a> ({{ tutor.education }})
          {% if not forloop.last %}, {% endif %}
      {% endfor %}
  </p>
  {% endif %}

  <h4> Темы</h4>
  <ul>
    {% if course.lesson_set.all %}
        {% for lesson in course.lesson_set.all %}
            <li><p>{{ lesson.title }}</p></li>
        {% endfor %}
    {% else %}
        <li><p>Темы пока не добавлены.</p></li>
    {% endif %}
  </ul>
  {% else %}
    <p>Нет обучающих курсов, но они обязательно появятся.</p>
  {% endif %}
{% endblock %}

schoolsite/school_app/templates/school_app/course_list.html
{% extends "base_generic.html" %}
{% load bootstrap %}

{% block content %}
    <h1>Наши курсы</h1>
    <p>В онлайн-школе обучение проходит по различным специальностям и имеет разную продолжительность:
        интенсивные семестровые, годовые и полуторагодовые программы.</p>
    <div class="container">

        <form method="GET">
            {{ filter.form|bootstrap }}
            <button type="submit" class="btn btn-primary">Найти</button>
        </form>

        {% if course_list %}
            {% if filter.qs %}
            <ul>
              {% for course in filter.qs %}
              <li>
                <a href="{{ course.get_absolute_url }}">{{ course.name }}</a> ({{course.duration}} месяцев)
                <p>{{ course.description }}</p>
                <p>Стоимость: <strong>{{ course.price }} рублей.</strong></p>
              </li>
              {% endfor %}
            </ul>
            {% else %}
                <p>К сожалению, такого курса пока нет...</p>
            {% endif %}
        {% else %}
          <p> Нет обучающих курсов.</p>
        {% endif %}
    </div>
{% endblock %}

schoolsite/school_app/templates/school_app/grade_form.html
{% extends "base_generic.html" %}
{% load bootstrap %}
{% block content %}
<h2>Изменить оценки</h2>

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form|bootstrap }}
    </table>
    <input type="submit" value="Отправить" />

</form>
{% endblock %}

schoolsite/school_app/templates/school_app/lesson_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h2>Удалить занятие</h2>

<p>Вы уверены, что хотите удалить занятие: {{ lesson.title }} ({{ lesson.course_id.name }})?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Да, удалить" />
</form>

{% endblock %}

schoolsite/school_app/templates/school_app/lesson_detail.html
{% extends "base_generic.html" %}

{% block content %}
  {% if lesson %}

  <h1>Занятие: {{ lesson.title }}</h1>
  <p><strong>Курс:</strong>
      <a href="{{ lesson.course_id.get_absolute_url }}">
              {{ lesson.course_id.name }}
      </a>
  </p>
  <p><strong>Преподаватель:</strong>
      <a href="{{ lesson.teacher_id.get_absolute_url }}">
              {{ lesson.teacher_id.name }}
      </a>
  </p>
  <p><strong>Ссылка на занятие:</strong>
      <a href="{{ lesson.link }}">
          видео.
      </a>
  </p>
  {% if user.is_teacher %}
      <p><strong><a href="{% url 'lesson_delete' lesson.pk %}">Удалить занятие</a></strong></p>
  {% endif %}
  {% else %}
    <p> Нет информации о занятии.</p>
  {% endif %}
{% endblock %}

schoolsite/school_app/templates/school_app/lesson_form.html
{% extends "base_generic.html" %}

{% load bootstrap %}
{% block content %}

<h2>Добавить занятие</h2>

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form|bootstrap }}
    </table>
    <input type="submit" value="Отправить" />

</form>
{% endblock %}

schoolsite/school_app/templates/school_app/lesson_list.html
{% extends "base_generic.html" %}
{% load bootstrap %}

{% block content %}
    <h1>Занятия</h1>

    <div class="container">

        <form method="GET" style="position:absolute; top:0px; right:200px">
            <h4>Примените фильтр для поиска</h4>
            {{ filter.form|bootstrap }}
            <button type="submit" class="btn btn-primary">Найти</button>
        </form>

        {% if lesson_list %}
            {% if filter.qs %}
            <ul>

              {% for lesson in filter.qs %}
              <li>
                <a href="{{ lesson.get_absolute_url }}">{{ lesson.title }}</a>
                <p>{{ lesson.course_id.name }}, {{ lesson.teacher_id.name }}</p>
              </li>
              {% endfor %}

            </ul>
            {% else %}
                <p>К сожалению, такого занятия нет...</p>
            {% endif %}
        {% else %}
          <p>Занятий пока нет...</p>
        {% endif %}
    </div>
{% endblock %}

schoolsite/school_app/templates/school_app/student_detail.html
{% extends "base_generic.html" %}

{% block content %}
  {% if student %}
  <h1>Студент: {{ student.name }}</h1>
  <p><strong>Электронная почта:</strong> {{ student.email }}.</p>
  <p><strong>Обучается на курсах:</strong>
        {% for grade in student.grade_set.all %}
            <a href="{{ grade.course.get_absolute_url }}">
                {{ grade.course.name }}
            </a>
        {% if not forloop.last %}, {% endif %}
        {% endfor %}
  </p>
  {% for grade in student.grade_set.all %}
      <h4>{{ grade.course.name }}</h4>
      <ul>
      <li>
          <p><strong>Оценка за 1 ДЗ:</strong>
          {% if grade.homework1 %}
              {{ grade.homework1 }}
          {% else %}
              пока нет.
          {% endif %}</p>
      </li>
      <li>
          <p><strong>Оценка за 2 ДЗ:</strong>
          {% if grade.homework2 %}
              {{ grade.homework2 }}
          {% else %}
              пока нет.
          {% endif %}
          </p>
      </li>
      <li>
          <p><strong>Оценка за проект:</strong>
          {% if grade.project %}
              {{ grade.project }}
          {% else %}
              пока нет.
          {% endif %}</p>
      </li>
      <li>
          <p><strong>Итоговая оценка за курс:</strong>
          {% if grade.final_mark %}
              {{ grade.final_mark|floatformat:2 }}
          {% else %}
              пока нет.
          {% endif %}</p>
      </li>
      </ul>
  {% endfor %}
  <br>
  {% if user.is_teacher %}
      {% for st in student.grade_set.all %}
      <h5><a href="{% url 'grades_update' st.pk %}">Изменить оценки </a>студента за курс {{ st.course }}</h5>
      {% endfor %}
  {% endif %}
  {% else %}
    <p> Нет информации о студенте.</p>
  {% endif %}
{% endblock %}

schoolsite/school_app/templates/school_app/student_grades_list.html
{% extends "base_generic.html" %}

{% block content %}

    {% if student_list %}
        {% for student in student_list %}
            <h2>Мои оценки: {{ student.name }}</h2>
            {% for grade in student.grade_set.all %}
              <h4>{{ grade.course.name }}</h4>
              <ul>
              <li>
                  <p><strong>Оценка за 1 ДЗ:</strong>
                  {% if grade.homework1 %}
                      {{ grade.homework1 }}
                  {% else %}
                      пока нет.
                  {% endif %}</p>
              </li>
              <li>
                  <p><strong>Оценка за 2 ДЗ:</strong>
                  {% if grade.homework2 %}
                      {{ grade.homework2 }}
                  {% else %}
                      пока нет.
                  {% endif %}
                  </p>
              </li>
              <li>
                  <p><strong>Оценка за проект:</strong>
                  {% if grade.project %}
                      {{ grade.project }}
                  {% else %}
                      пока нет.
                  {% endif %}</p>
              </li>
              <li>
                  <p><strong>Итоговая оценка за курс:</strong>
                  {% if grade.final_mark %}
                      {{ grade.final_mark|floatformat:2 }}
                  {% else %}
                      пока нет.
                  {% endif %}</p>
              </li>
              </ul>
            {% endfor %}
        {% endfor %}
    {% endif %}
{% endblock %}

schoolsite/school_app/templates/school_app/student_list.html
{% extends "base_generic.html" %}
{% load bootstrap %}

{% block content %}
    <h1>Наши cтуденты</h1>

    <div class="container">

        <form method="GET">
            <h4>Примените фильтр для поиска</h4>
            {{ filter.form|bootstrap }}
            <button type="submit" class="btn btn-primary">Найти</button>
        </form>

        {% if student_list %}
            {% if filter.qs %}
            <ul>
              {% for student in filter.qs %}
              <li>
                <a href="{{ student.get_absolute_url }}">{{ student.name }}</a> ({{ student.email }})
                <p><strong>Обучается на курсах:</strong>
                {% for course in student.course_set.all %}
                    <a href="{{ course.get_absolute_url }}">
                        {{ course.name }}
                    </a>
                {% if not forloop.last %}, {% endif %}
                {% endfor %}
                </p>
              </li>
              {% endfor %}
            </ul>
            {% else %}
                <p>К сожалению, такого студента нет...</p>
            {% endif %}
        {% else %}
          <p>У нас пока никто не обучается...</p>
        {% endif %}
    </div>
{% endblock %}

schoolsite/school_app/templates/school_app/teacher_detail.html
{% extends "base_generic.html" %}

{% block content %}
  {% if teacher %}
  <h1>Преподаватель: {{ teacher.name }}</h1>

  <p><strong>Электронная почта:</strong> {{ teacher.email }}.</p>
  <p><strong>Место основной работы:</strong> {{ teacher.company }}.</p>
  <p><strong>Опыт:</strong> {{ teacher.experience }} лет.</p>
  <p><strong>Образование:</strong> {{ teacher.education }}.</p>
  <p><strong>Роль:</strong> {{ teacher.role }}.</p>
  <p><strong>Преподаёт на курсах:</strong>
      {% for course in teacher.course_set.all %}
          <a href="{{ course.get_absolute_url }}">
              {{ course.name }}
          </a>
          {% if not forloop.last %}, {% endif %}
      {% endfor %}
  </p>

  {% else %}
    <p>Пока что нет информации о преподавателе.</p>
  {% endif %}
{% endblock %}

schoolsite/school_app/templates/school_app/teacher_list.html
{% extends "base_generic.html" %}
{% load bootstrap %}

{% block content %}
    <h1>Наши преподаватели</h1>
    <p>Преподаватели — самые опытные и понимающие.
    </p>

    <div class="container">

        <form method="GET">
            {{ filter.form|bootstrap }}
            <button type="submit" class="btn btn-primary">Найти</button>
        </form>

        {% if teacher_list %}
            {% if filter.qs %}
            <ul>

              {% for teacher in filter.qs %}
              <li>
                <a href="{{ teacher.get_absolute_url }}">{{ teacher.name }}</a> (работает в {{ teacher.company }})
                <p><strong>Преподаёт на курсах:</strong>
                {% for course in teacher.course_set.all %}
                    <a href="{{ course.get_absolute_url }}">
                        {{ course.name }}
                    </a>
                {% if not forloop.last %}, {% endif %}
                {% endfor %}
                </p>
              </li>
              {% endfor %}
            </ul>
            {% else %}
                <p>К сожалению, такого преподавателя нет...</p>
            {% endif %}
        {% else %}
          <p>К нам пока никто не устроился...</p>
        {% endif %}
    </div>
{% endblock %}

schoolsite/school_app/templates/school_app/tutor_detail.html
{% extends "base_generic.html" %}

{% block content %}
  {% if tutor %}
  <h1>Куратор: {{ tutor.name }}</h1>

  <p><strong>Электронная почта:</strong> {{ tutor.email }}.</p>
  <p><strong>Образование:</strong> {{ tutor.education }}.</p>
  <p><strong>Наставляет студентов на курсах:</strong>
      {% for course in tutor.course_set.all %}
          <a href="{{ course.get_absolute_url }}">
              {{ course.name }}
          </a>
          {% if not forloop.last %}, {% endif %}
      {% endfor %}
  </p>

  {% else %}
    <p> Нет информации о кураторе.</p>
  {% endif %}
{% endblock %}

schoolsite/school_app/templates/school_app/tutor_list.html
{% extends "base_generic.html" %}
{% load bootstrap %}

{% block content %}
    <h1>Наши кураторы</h1>
    <p>Наставники всегда помогут.</p>
    <p>Обратиться к ним можно по любым вопросам - и по учебным, и по личным.</p>

    <div class="container">

        <form method="GET" style="position:absolute; top:0px; right:100px">
            <h4>Примените фильтр для поиска</h4>
            {{ filter.form|bootstrap }}
            <button type="submit" class="btn btn-primary">Найти</button>
        </form>

        {% if tutor_list %}
            {% if filter.qs %}
            <ul>

              {% for tutor in filter.qs %}
              <li>
                <a href="{{ tutor.get_absolute_url }}">{{ tutor.name }}</a> ({{ tutor.education }})
                <p><strong>Наставляет студентов на курсах:</strong>
                {% for course in tutor.course_set.all %}
                    <a href="{{ course.get_absolute_url }}">
                        {{ course.name }}
                    </a>
                {% if not forloop.last %}, {% endif %}
                {% endfor %}
                </p>
              </li>
              {% endfor %}

            </ul>
            {% else %}
                <p>К сожалению, такого куратора нет...</p>
            {% endif %}
        {% else %}
          <p>Кураторов пока нет...</p>
        {% endif %}
    </div>
{% endblock %}